### ISSUE TITLE
PFRL for discrete actions with continuous parameters

### ISSUE THREAD

**Issue by SpaceGhost123** [pfnet/pfrl#120]
Hi all,

I am working on an RL problem that has discrete actions, but each action has a continuous parameter. I would be appreciative of any advice you could give me as to how to get going within the PFRL framework.

Thanks,

~Space Ghost

**Comment by muupan** [comment]
I have no experience of working on such an action space and don't know sure what works best, but there are several possible ways to support it.
- Discretize the continuous parameter space so that the whole action space is discrete, which I think would be easiest if possible.
- Represent an action distribution as joint distribution over discrete and continuous variables (e.g. https://arxiv.org/abs/2001.00449) and use any algorithm that can train a stochastic policy . You would need to implement your own distribution class extending `torch.distributions.Distribution`.
- Implement your own ActionValue class extending `pfrl.action_value.ActionValue` for a joint action space where you approximate `argmax` over continuous variables in some way, e.g. by CEM https://arxiv.org/abs/1806.10293, and use DQN etc to train a Q-network.

**Comment by SpaceGhost123** [comment]
Thanks muupan. I am proceeding with the second idea you suggested of creating a joint distribution.
